//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class admin
    {
        public long ID { get; set; }

        [Required(ErrorMessage ="Username Required")]
        public string unm { get; set; }

        //[Required(ErrorMessage = "Password Required")]
        public string pwd { get; set; }

        public string newpass { get; set; }
        public string oldpass { get; set; }

        [Required(ErrorMessage = "Email Cannot be blank")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        public string modifyip { get; set; }
        public string mshost { get; set; }
        public string msusername { get; set; }
        public string mspass { get; set; }
        public Nullable<System.DateTime> Backupdt { get; set; }
    }
}
