//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminlog
    {
        public long id { get; set; }
        public string unm { get; set; }
        public string password { get; set; }
        public string aip { get; set; }
        public Nullable<System.DateTime> adate { get; set; }
        public Nullable<bool> asucess { get; set; }
    }
}
