//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appdevice
    {
        public long id { get; set; }
        public string deviceid { get; set; }
        public string devicetype { get; set; }
        public string deviceinfo { get; set; }
        public Nullable<System.DateTime> addeddate { get; set; }
        public string addedip { get; set; }
        public string Email { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
