//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class area
    {
        public long id { get; set; }
        public Nullable<long> cityid { get; set; }

        [Required(ErrorMessage = "Name Cannot be Blank")]
        public string Name { get; set; }

        public Nullable<bool> visible { get; set; }
        public Nullable<System.DateTime> addeddate { get; set; }
        public string addedip { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public string modifyip { get; set; }

        [Required(ErrorMessage = "Shipping Charge Cannot be Blank")]
        //[RegularExpression("^[0-9]{1,12}$", ErrorMessage = "Shipping Charge Must be Numeric")]
        [RegularExpression(@"^[0-9]\d{0,9}(\.\d{1,3})?%?$", ErrorMessage ="Invalid Shipping charge")]
        public Nullable<decimal> shippingcharge { get; set; }

        [Required(ErrorMessage = "Minimum Charge Cannot be Blank")]
        //[RegularExpression("^[0-9]{1,12}$", ErrorMessage = "Minimum Charge Must be Numeric")]
        [RegularExpression(@"^[0-9]\d{0,9}(\.\d{1,3})?%?$", ErrorMessage = "Invalid Minimum charge")]
        public Nullable<decimal> minimumcharge { get; set; }
    }
}
