//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class areaselected
    {
        public long id { get; set; }
        public Nullable<long> areaid { get; set; }
        public Nullable<long> dealerid { get; set; }

        public bool ischecked { get; set; }
    }
    
}
