//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sabziappEntities : DbContext
    {
        public sabziappEntities()
            : base("name=sabziappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<addressbook> addressbooks { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<adminlog> adminlogs { get; set; }
        public virtual DbSet<appdevice> appdevices { get; set; }
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<areaselected> areaselecteds { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<currentversion> currentversions { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<dealer> dealers { get; set; }
        public virtual DbSet<dealersnotification> dealersnotifications { get; set; }
        public virtual DbSet<deliveryslot> deliveryslots { get; set; }
        public virtual DbSet<dist_state> dist_state { get; set; }
        public virtual DbSet<emailtemplate> emailtemplates { get; set; }
        public virtual DbSet<enquiry> enquiries { get; set; }
        public virtual DbSet<faq> faqs { get; set; }
        public virtual DbSet<faqcategory> faqcategories { get; set; }
        public virtual DbSet<faqenquiry> faqenquiries { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<homebanner> homebanners { get; set; }
        public virtual DbSet<insidepage> insidepages { get; set; }
        public virtual DbSet<newslettercampaign> newslettercampaigns { get; set; }
        public virtual DbSet<newslettergroup> newslettergroups { get; set; }
        public virtual DbSet<newslettersendhistory> newslettersendhistories { get; set; }
        public virtual DbSet<newslettersubscriber> newslettersubscribers { get; set; }
        public virtual DbSet<newslettertemplate> newslettertemplates { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<orderitem> orderitems { get; set; }
        public virtual DbSet<ordermaster> ordermasters { get; set; }
        public virtual DbSet<pricemanager> pricemanagers { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productcategory1> productcategory1 { get; set; }
        public virtual DbSet<productcategory2> productcategory2 { get; set; }
        public virtual DbSet<redeedmvippoint> redeedmvippoints { get; set; }
        public virtual DbSet<refundhistory> refundhistories { get; set; }
        public virtual DbSet<searchhistory> searchhistories { get; set; }
        public virtual DbSet<sendnewsletterscheduler> sendnewsletterschedulers { get; set; }
        public virtual DbSet<shippingcharge> shippingcharges { get; set; }
        public virtual DbSet<siteprofile> siteprofiles { get; set; }
        public virtual DbSet<specialpricemanager> specialpricemanagers { get; set; }
        public virtual DbSet<specialproduct> specialproducts { get; set; }
        public virtual DbSet<specialproductimage> specialproductimages { get; set; }
        public virtual DbSet<specialstockmanager> specialstockmanagers { get; set; }
        public virtual DbSet<stockmanager> stockmanagers { get; set; }
        public virtual DbSet<subscription> subscriptions { get; set; }
        public virtual DbSet<subscriptionselected> subscriptionselecteds { get; set; }
        public virtual DbSet<supporttype> supporttypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tax> taxes { get; set; }
        public virtual DbSet<testimonial> testimonials { get; set; }
        public virtual DbSet<ticketdetail> ticketdetails { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<voucher> vouchers { get; set; }
        public virtual DbSet<voucheruser> voucherusers { get; set; }
        public virtual DbSet<wallet> wallets { get; set; }
        public virtual DbSet<sampleproduct> sampleproducts { get; set; }
        public virtual DbSet<sampleproductimage> sampleproductimages { get; set; }
    }
}
