//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class dealer
    {
        public long id { get; set; }

        [Required(ErrorMessage = "Name is Required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Address is Required")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Landmark is Required")]
        public string Landmark { get; set; }

        [Required(ErrorMessage = "City is Required")]
        public Nullable<long> City { get; set; }

        public Nullable<long> State { get; set; }

        [Required(ErrorMessage = "PostCode is Required")]
        [RegularExpression(@"^\d{6}(-\d{4})?$", ErrorMessage = "Please Enter Valid Postal Code.")]
        public string PostCode { get; set; }

        [Required(ErrorMessage = "Email is Required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is Required")]
        public string Password { get; set; }
        

        [NotMapped]
        public string OldPassword { get; set;}

        [NotMapped]
        public string NewPassword { get; set; }


        [Required(ErrorMessage = "Phone is Required")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Mobile Number.")]
        public string Phone { get; set; }
        
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Addeddate { get; set; }
        public string Addedip { get; set; }
        public Nullable<System.DateTime> Modifydate { get; set; }
        public string Modifyip { get; set; }
        public Nullable<bool> numConfirmed { get; set; }
        public Nullable<byte> unread { get; set; }

        [Required(ErrorMessage = "Slot Description is Required")]
        public string SlotDescription { get; set; }

        [Required(ErrorMessage = "Other Area is Required")]
        public string otherarea { get; set; }
    }
}
