//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class insidepage
    {
        public long ID { get; set; }
        public string PageName { get; set; }
        public string PageIETitle { get; set; }
        public string PageDesc { get; set; }
        public string Meta { get; set; }
        public string addedip { get; set; }
        public Nullable<System.DateTime> addeddate { get; set; }
        public string modifyip { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public Nullable<long> sortorder { get; set; }
    }
}
