//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newslettergroup
    {
        public long id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> addeddate { get; set; }
        public string addedIp { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyIp { get; set; }
    }
}
