//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newslettersendhistory
    {
        public long id { get; set; }
        public Nullable<long> CampaignId { get; set; }
        public string ToMail { get; set; }
        public string ToName { get; set; }
    }
}
