//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderitem
    {
        public long id { get; set; }
        public Nullable<long> Ordid { get; set; }
        public Nullable<long> pid { get; set; }
        public Nullable<long> cat1id { get; set; }
        public Nullable<long> cat2id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string HindiTitle { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Unit { get; set; }
        public Nullable<long> Qty { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> Delivery { get; set; }
        public string priceDesc { get; set; }
        public string specialInstruction { get; set; }
        public Nullable<long> SpecialType { get; set; }
        public Nullable<long> itempriceid { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
    }
}
