//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordermaster
    {
        public long id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Postcode { get; set; }
        public string Landmark { get; set; }
        public string Phone { get; set; }
        public string BName { get; set; }
        public string BEmail { get; set; }
        public string BAddress { get; set; }
        public string BCity { get; set; }
        public string BState { get; set; }
        public string BPostCode { get; set; }
        public string BLandmark { get; set; }
        public string BPhone { get; set; }
        public Nullable<long> uid { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Grandtotal { get; set; }
        public Nullable<decimal> Delivery { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<System.DateTime> Orderdate { get; set; }
        public string Orderip { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<long> OrderStatus { get; set; }
        public Nullable<long> GiftCodeType { get; set; }
        public string ordernumber { get; set; }
        public Nullable<byte> unread { get; set; }
        public string Admincomments { get; set; }
        public Nullable<long> AutoProcessDone { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyIp { get; set; }
        public string DiscountDESC { get; set; }
        public Nullable<decimal> FromWallet { get; set; }
        public Nullable<long> Express { get; set; }
        public string DeliveryOn { get; set; }
        public string paymentmode { get; set; }
        public string Ordertime { get; set; }
        public Nullable<long> dealerid { get; set; }
        public Nullable<byte> israting { get; set; }
        public string rating { get; set; }
        public string review { get; set; }
    }
}
