//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialpricemanager
    {
        public long id { get; set; }
        public Nullable<long> Weight { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> APrice { get; set; }
        public Nullable<decimal> DPrice { get; set; }
        public Nullable<long> productid { get; set; }
        public string Unit { get; set; }
    }
}
