//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockmanager
    {
        public long id { get; set; }
        public Nullable<long> Areaid { get; set; }
        public Nullable<long> productid { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<long> reorderlevel { get; set; }
    }
}
