//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class subscription
    {
        public long id { get; set; }

        [Required(ErrorMessage = "Name Cannot be Blank")]
        public string Name { get; set; }

        public Nullable<long> month { get; set; }
        [Required(ErrorMessage = "Days Cannot be Blank")]
        [RegularExpression("^[0-9]{1,12}$", ErrorMessage = "Days Must be Numeric")]
        public Nullable<long> days { get; set; }

        [Required(ErrorMessage = "Amount Cannot be Blank")]
        [RegularExpression(@"^[0-9]\d{0,9}(\.\d{1,3})?%?$", ErrorMessage = "Amount Must be Numeric")]
        public Nullable<decimal> amount { get; set; }

        public Nullable<bool> Visible { get; set; }
        public Nullable<System.DateTime> addeddate { get; set; }
        public string addedip { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public string modifyip { get; set; }
    }
}
