//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax
    {
        public long id { get; set; }
        public Nullable<decimal> ProductTax { get; set; }
        public Nullable<decimal> RestTax { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyIp { get; set; }
    }
}
