//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public long id { get; set; }
        public Nullable<long> customerid { get; set; }
        public string subject { get; set; }
        public string ticketid { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> replystatus { get; set; }
        public string supportfor { get; set; }
        public Nullable<System.DateTime> Addeddate { get; set; }
        public string Addedip { get; set; }
        public Nullable<System.DateTime> closedate { get; set; }
        public Nullable<System.DateTime> reopendate { get; set; }
        public Nullable<byte> adminunread { get; set; }
        public Nullable<byte> Dealerunread { get; set; }
    }
}
