//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ticketdetail
    {
        public long id { get; set; }

        [Required(ErrorMessage = "Name Cannot be Empty")]
        public string Name { get; set; }

        public Nullable<long> ticketid { get; set; }
        public string comments { get; set; }
        public Nullable<bool> replytype { get; set; }
        public Nullable<System.DateTime> Addeddate { get; set; }
        public string Addedip { get; set; }
        public Nullable<System.DateTime> Modifydate { get; set; }
        public string Modifyip { get; set; }
    }
}
