//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucheruser
    {
        public long id { get; set; }
        public Nullable<long> VoucherID { get; set; }
        public string UserEmail { get; set; }
        public Nullable<bool> Used { get; set; }
        public Nullable<bool> EMailSend { get; set; }
        public string Username { get; set; }
    }
}
