//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veggiesapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class wallet
    {
        public long id { get; set; }
        
        public Nullable<decimal> addamount { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<long> uid { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
    }
}
